services:
    postgres:
        image: bitnami/postgresql:latest
        container_name: postgres_api_gerenciamento
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/bitnami/postgresql

volumes:
    postgres_data:
